### ISSUE TITLE
Zulipbot does not work as expected when sending repo invites

### ISSUE THREAD

**Issue by cPhost** [zulip/zulipbot#141] opened 2017-12-14 01:28 UTC
Sometimes when we claim and issue by @-zulipbot claim it comments stating you "we just sent you an invite to collaborate" and then when you actually click the link it does not work.

Happened two times. 
Refs: https://github.com/zulip/zulip/issues/7567#issuecomment-350135417
Refs: https://github.com/zulip/zulip-mobile/issues/1455#issuecomment-351500999

**Comment by synicalsyntax** [comment] 2017-12-14 02:23
So, this is either GitHub fault's for neither registering an invite nor throwing an error to let us know that invite creation failed or ours for not handling any errors returned from the API. I think it's the former, since there are only 2 instances of this happening among dozens of invites sent and the issue is not reproducible on my end. I'll have a better idea when I get to see the log output, but I don't have access to them now.

Also, for future reference, you can reference a zulipbot command within codeblocks like so: `@zulipbot claim`.

**Comment by synicalsyntax** [comment] 2017-12-14 20:45
Looks like the GitHub API threw back an internal server error to the request. Closing the issue as it isn't our fault.

**Closed by synicalsyntax** 2017-12-14 20:45 UTC
Labels: bug
