### ISSUE TITLE
Make sure references are issues for "Fixes #1234" notifications

### ISSUE THREAD

**Issue by lonerz** [zulip/zulipbot#119] opened 2017-08-24 19:43 UTC
For example in this [PR](https://github.com/zulip/zulip/pull/6258#issuecomment-324568841), someone references another pull request, so zulipbot shouldn't try to have the PR author to have `Fixes #1234` in their commit message.

Somewhat related to #118

**Comment by synicalsyntax** [comment] 2017-08-24 20:34
Duplicate of #118.

**Closed by synicalsyntax** 2017-08-24 20:34 UTC
Labels: bug
