### ISSUE TITLE
Screening labels before adding

### ISSUE THREAD

**Issue by lonerz** [zulip/zulipbot#6] opened 2017-02-23 08:25 UTC
We don't want to add labels that have not existed before in the organization. See [this issue](https://github.com/zulip/zulip/issues/3771). There should be a way to filter these labels out.

**Comment by janga1997** [comment] 2017-02-23 08:35
@lonerz Is this something I could work on?

**Comment by lonerz** [comment] 2017-02-23 08:43
@janga1997 you can work on it, follow the README.md to install

**Comment by lonerz** [comment] 2017-02-23 09:10
@zulipbot claim

**Comment by janga1997** [comment] 2017-02-23 09:29
@lonerz @synicalsyntax What I was asking for, is a way to see if my changes actually work as intended.

**Comment by synicalsyntax** [comment] 2017-02-23 16:02
@janga1997 Currently I have created an organization on a test account of mine, and I have @zulipbot-test deployed on Heroku for testing purposes. But yes, I agree that we need to have a better way to test any changes of @zulipbot, like adding continuous integration and unit testing in the future. 

If you have any suggestions on what we can do, please join us on the [zulipbot topic](https://chat.zulip.org/#narrow/topic/zulipbot.20is.20alive!) on the developer chat. Thanks for your interest!

I'm currently working on this issue, by the way; just a heads up :)

**Comment by synicalsyntax** [comment] 2017-02-24 03:30
Fixed in f5228a0

**Closed by synicalsyntax** 2017-02-24 03:30 UTC

**Comment by synicalsyntax** [comment] 2017-02-26 20:27
@zulipbot claim
